name: Check links

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

permissions:
  contents: read
  issues: write

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel nbconvert

      - name: Convert notebooks to markdown
        run: |
          find . -name "*.ipynb" -exec jupyter nbconvert --to markdown {} \;

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --exclude-path docs/broken_link.md -- .

      - name: Create issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Check links failed'
          content-filepath: ./lychee/out.md
          labels: |
            docs
          assignees: |
            mrsmrynk
